env:
  es6: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - dist
extends:
  - '@alex-taxiera/eslint-config-cjs'
overrides:
  -
    files:
      - '*.ts'
    parserOptions:
      project:
        - ./tsconfig.json
    extends:
      - '@alex-taxiera/eslint-config-ts'
    rules:
      comma-dangle: off
      '@typescript-eslint/strict-boolean-expressions': ['error', {
        allowString: true,
        allowNumber: false,
        allowNullableObject: true,
        allowNullableBoolean: true,
        allowNullableString: true,
        allowNullableNumber: false,
        allowAny: true
      }]
