name: Publish

on:
  push:
    branches:
      - master
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO }}
          tags: "${{ secrets.NAME }},${{ secrets.NAME }}-${{ github.RUN_NUMBER }},${{ secrets.NAME }}-${{ steps.extract_branch.outputs.branch }},${{ secrets.NAME }}-${{ steps.extract_branch.outputs.branch }}-${{ github.RUN_NUMBER }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
