name: Publish

on:
  push:
    branches:
      - master
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO }}
          tags: "${{ secrets.NAME }},${{ secrets.NAME }}-${{ steps.buildnumber.outputs.build_number }},${{ secrets.NAME }}-${{ steps.extract_branch.outputs.branch }},${{ secrets.NAME }}-${{ steps.extract_branch.outputs.branch }}-${{ steps.buildnumber.outputs.build_number }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
