name: Lint and Compile

on: [pull_request]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    -
      run: npm ci
    -
      run: npx tsc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    -
      run: npm ci
    -
      run: npm run lint
