name: Release

on:
  repository_dispatch:
    types: [release]

jobs:
  push_to_docker_hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.client_payload.sha }}
      -
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO }}
          tags: "${{ secrets.NAME }},${{ secrets.NAME }}-${{ github.RUN_NUMBER }},${{ secrets.NAME }}-${{ github.event.client_payload.branch }},${{ secrets.NAME }}-${{ github.event.client_payload.branch }}-${{ github.RUN_NUMBER }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
